
e1 = Event.find_by_name('Randy Clark 2-4.06')
e2 = Event.find_by_name('Blaine Cook 25-27.04')
e3 = Event.find_by_name('Gary Oates 16-18.05')
r1 = Role.find_by(name: 'Uczestnik', event_id: e1.id)
r2 = Role.find_by(name: 'Gość', event_id: e1.id)
r3 = Role.find_by(name: 'Uczestnik', event_id: e2.id)
r4 = Role.find_by(name: 'Uczestnik', event_id: e3.id)

sg = ServiceGroup.create!(name: 'Dodatkowe')
s1 = Service.create!(name: 'Informacje o kolejnych wydarzeniach', event: e1, service_group: sg, description: "Zgoda na informacje o kolejnych wydarzeniach")
s2 = Service.create!(name: 'Informacje o kolejnych wydarzeniach', event: e2, service_group: sg, description: "Zgoda na informacje o kolejnych wydarzeniach")
s3 = Service.create!(name: 'Informacje o kolejnych wydarzeniach', event: e3, service_group: sg, description: "Zgoda na informacje o kolejnych wydarzeniach")
ServicePrice.create!(price: 0, role: r1, service: s1)
ServicePrice.create!(price: 0, role: r1, service: s2)
ServicePrice.create!(price: 0, role: r1, service: s3)
ServicePrice.create!(price: 0, role: r2, service: s1)
ServicePrice.create!(price: 0, role: r2, service: s2)
ServicePrice.create!(price: 0, role: r2, service: s3)
ServicePrice.create!(price: 0, role: r3, service: s1)
ServicePrice.create!(price: 0, role: r3, service: s2)
ServicePrice.create!(price: 0, role: r3, service: s3)
ServicePrice.create!(price: 0, role: r4, service: s1)
ServicePrice.create!(price: 0, role: r4, service: s2)
ServicePrice.create!(price: 0, role: r4, service: s3)
puts "Services #{sg.name} created!"
